// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpdRnwroyWrFqJsU_vLesiw2EOaUtI64',
    appId: '1:252564467226:web:de8be0f5ac17c5c9b86ba3',
    messagingSenderId: '252564467226',
    projectId: 'portfolio-9c379',
    authDomain: 'portfolio-9c379.firebaseapp.com',
    storageBucket: 'portfolio-9c379.appspot.com',
    measurementId: 'G-4YXG9S3GJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlD2-i-hhz8myHkMB3FsmC1WnO4O7bXw',
    appId: '1:252564467226:android:01d701e6b3dcdf0fb86ba3',
    messagingSenderId: '252564467226',
    projectId: 'portfolio-9c379',
    storageBucket: 'portfolio-9c379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRabCLJCJcU8H0-FVb2HmOM7Nex6IDyk',
    appId: '1:252564467226:ios:c04dc0175414bef3b86ba3',
    messagingSenderId: '252564467226',
    projectId: 'portfolio-9c379',
    storageBucket: 'portfolio-9c379.appspot.com',
    iosBundleId: 'com.example.hamroShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaRabCLJCJcU8H0-FVb2HmOM7Nex6IDyk',
    appId: '1:252564467226:ios:c04dc0175414bef3b86ba3',
    messagingSenderId: '252564467226',
    projectId: 'portfolio-9c379',
    storageBucket: 'portfolio-9c379.appspot.com',
    iosBundleId: 'com.example.hamroShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWpdRnwroyWrFqJsU_vLesiw2EOaUtI64',
    appId: '1:252564467226:web:5d23cac31a4ae032b86ba3',
    messagingSenderId: '252564467226',
    projectId: 'portfolio-9c379',
    authDomain: 'portfolio-9c379.firebaseapp.com',
    storageBucket: 'portfolio-9c379.appspot.com',
    measurementId: 'G-5D940XSTKZ',
  );
}
